//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.0
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pocal.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pocal.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All day ähnelt.
        /// </summary>
        public static string allDay {
            get {
                return ResourceManager.GetString("allDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die and ähnelt.
        /// </summary>
        public static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die add ähnelt.
        /// </summary>
        public static string AppBarAdd {
            get {
                return ResourceManager.GetString("AppBarAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        public static string AppBarBack {
            get {
                return ResourceManager.GetString("AppBarBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Today ähnelt.
        /// </summary>
        public static string AppBarButtonToday {
            get {
                return ResourceManager.GetString("AppBarButtonToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die overview ähnelt.
        /// </summary>
        public static string AppBarCloseOverview {
            get {
                return ResourceManager.GetString("AppBarCloseOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Go to ähnelt.
        /// </summary>
        public static string AppBarGoTo {
            get {
                return ResourceManager.GetString("AppBarGoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die days ähnelt.
        /// </summary>
        public static string DayPlural {
            get {
                return ResourceManager.GetString("DayPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die day ähnelt.
        /// </summary>
        public static string DaySingular {
            get {
                return ResourceManager.GetString("DaySingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die in ähnelt.
        /// </summary>
        public static string futureTime {
            get {
                return ResourceManager.GetString("futureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hours ähnelt.
        /// </summary>
        public static string HourPlural {
            get {
                return ResourceManager.GetString("HourPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hour ähnelt.
        /// </summary>
        public static string HourSingular {
            get {
                return ResourceManager.GetString("HourSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you like this app and you want to buy it, please visit the store:  ähnelt.
        /// </summary>
        public static string InfoBuyRate {
            get {
                return ResourceManager.GetString("InfoBuyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you find a bug or missing a feature, please send me an email so that I can look into it. ähnelt.
        /// </summary>
        public static string InfoFeedback {
            get {
                return ResourceManager.GetString("InfoFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die link to store ähnelt.
        /// </summary>
        public static string InfoLinkStore {
            get {
                return ResourceManager.GetString("InfoLinkStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thank you for using Pocal! ähnelt.
        /// </summary>
        public static string InfoThanks {
            get {
                return ResourceManager.GetString("InfoThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can also follow me on Twitter. ähnelt.
        /// </summary>
        public static string InfoTwitter {
            get {
                return ResourceManager.GetString("InfoTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Week ähnelt.
        /// </summary>
        public static string KW {
            get {
                return ResourceManager.GetString("KW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die minutes ähnelt.
        /// </summary>
        public static string MinutePlural {
            get {
                return ResourceManager.GetString("MinutePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die minute ähnelt.
        /// </summary>
        public static string MinuteSingular {
            get {
                return ResourceManager.GetString("MinuteSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fri ähnelt.
        /// </summary>
        public static string MonthViewFri {
            get {
                return ResourceManager.GetString("MonthViewFri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mon ähnelt.
        /// </summary>
        public static string MonthViewMon {
            get {
                return ResourceManager.GetString("MonthViewMon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sat ähnelt.
        /// </summary>
        public static string MonthViewSat {
            get {
                return ResourceManager.GetString("MonthViewSat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sun ähnelt.
        /// </summary>
        public static string MonthViewSun {
            get {
                return ResourceManager.GetString("MonthViewSun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thu ähnelt.
        /// </summary>
        public static string MonthViewThu {
            get {
                return ResourceManager.GetString("MonthViewThu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tue ähnelt.
        /// </summary>
        public static string MonthViewTue {
            get {
                return ResourceManager.GetString("MonthViewTue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wed ähnelt.
        /// </summary>
        public static string MonthViewWed {
            get {
                return ResourceManager.GetString("MonthViewWed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ago ähnelt.
        /// </summary>
        public static string pastTime {
            get {
                return ResourceManager.GetString("pastTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LeftToRight ähnelt.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die en ähnelt.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die en-US ähnelt.
        /// </summary>
        public static string ResourceLanguage1 {
            get {
                return ResourceManager.GetString("ResourceLanguage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sunday red ähnelt.
        /// </summary>
        public static string SettingsSundayRed {
            get {
                return ResourceManager.GetString("SettingsSundayRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die today ähnelt.
        /// </summary>
        public static string today {
            get {
                return ResourceManager.GetString("today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die tomorrow ähnelt.
        /// </summary>
        public static string tomorrow {
            get {
                return ResourceManager.GetString("tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have {0} days of your trial left. If you like this app, you can buy it at the store. ähnelt.
        /// </summary>
        public static string trialPopup {
            get {
                return ResourceManager.GetString("trialPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die weeks ähnelt.
        /// </summary>
        public static string WeekPlural {
            get {
                return ResourceManager.GetString("WeekPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die week ähnelt.
        /// </summary>
        public static string WeekSingular {
            get {
                return ResourceManager.GetString("WeekSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die yesterday ähnelt.
        /// </summary>
        public static string yesterday {
            get {
                return ResourceManager.GetString("yesterday", resourceCulture);
            }
        }
    }
}
